import { Component, OnInit, ViewChild } from '@angular/core';
import { UntypedFormControl, Validators } from '@angular/forms';
import { MessageService } from 'primeng/api';
import { CommonService } from 'src/app/common-methods/services/common.service';
import { InvoiceService } from 'src/app/common-methods/services/invoice.service';
import { PageChangeEvent, GridDataResult } from '@progress/kendo-angular-grid';
// import { DataTable, LazyLoadEvent } from 'primeng/primeng';
import { UserData } from 'src/app/common-methods/models/user';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/common-methods/services/auth.service';
import { Table } from 'primeng/table';
import { LazyLoadEvent } from 'primeng/api';
// import { MessageService } from 'primeng/api';

@Component({
  standalone: false,
  selector: 'app-manual-reg-invoice',
  templateUrl: './manual-reg-invoice.component.html',
  styleUrls: ['./manual-reg-invoice.component.css']
})
export class ManualRegInvoiceComponent implements OnInit {
  public gridView: GridDataResult;
  public buttonCount = 7;
  public info = true;
  public type: 'numeric' | 'input' = 'numeric';
  public pageSizes = true;
  public previousNext = true;
  public skip = 0;
  itemperpage;
  totalpages: number;
  currentPage = 1;
  tempCurrentPage = 1;
   @ViewChild('dt', { static: false }) dt!: Table;
  event: LazyLoadEvent;
  loading: boolean;
  shieveTotalCount = 0;
  shievePageNo = 1;
  shievePageSize = 10;
  ExcelFlag: boolean = false;
  isShowAll:boolean = false;
  agentvalue: any[] = [];
  mySelection: any[] = [];
  SkipInvoiceList: any[] = [];
  selectedBindList: any[] = [];
  btnApprove = false;
  unBilledInvoiceList: any[] = [];
  unBilledInvoiceExpList: any[] = []; 
  clientId = new UntypedFormControl(null);
  fromDate = new UntypedFormControl('');
  toDate = new UntypedFormControl('');
  invoiceDate = new UntypedFormControl('');
  skipInvoiceNo = new UntypedFormControl('');
  userData: UserData;
  monthly = new UntypedFormControl('');
  screenAuth: any = {};
  displayColumns = [
    { field: 'clientName', header: 'Client Name' },
     { field: 'siteName', header: 'Site Name' },
  { field: 'state', header: 'State' },
   { field: 'gstNumber', header: 'Gst Number' },
  { field: 'clientAccountManager', header: 'Client Account Manager' },
  { field: 'salesPersonName', header: 'Sales Person Name' },
      { field: 'invoiceStatus', header: 'Invoice Status' },
   { field: 'invoiceGeneratedOn', header: 'Invoice Generated On' },
  { field: 'invoiceNumber', header: 'Invoice Number' },
  { field: 'invoiceValue', header: 'Invoice Value' },
  { field: 'invoiceGeneratedBy', header: 'Invoice Generated By' }];
  constructor(private invoiceService: InvoiceService, public commonService: CommonService, private message: MessageService , public router: Router, private auth: AuthService) { }
  ngOnInit() {
    this.userData = JSON.parse(sessionStorage.getItem('user_data') as string);
    this.screenAuth = this.auth.getScreenAuth(this.router.url);
    this.getInvoiceClient();
    this.manualInvoiceList();
    this.itemperpage = 10;
  }
  getInvoiceClient() {
    this.invoiceService.getInvoiceClient(this.userData.clientId).subscribe(res => {
      this.agentvalue = res;
    });
  }
  manualInvoiceList() {
    this.invoiceService.getManualInvoiceList().subscribe(res => {
        this.SkipInvoiceList = res;
    });
  }
  resetList() {
    this.clientId.reset('');
    this.fromDate.reset('');
    this.toDate.reset('');
    this.unBilledInvoiceList = [];
    this.monthly.reset('');
    this.gridView = {
      data:[],
      total:0
    };
  }
  resetInvoice() {
    this.selectedBindList = [];
    this.skipInvoiceNo.reset('');
    this.invoiceDate.reset('');
  }
  addManualInvoice() {
    if (this.selectedBindList.length > 0) {
    const screeninglist = this.selectedBindList.map(x => x.screeningId);
    if (this.skipInvoiceNo.value) {
      const manualInvoiceVm = {
        screening: screeninglist,
        skipInvoiceNo : this.skipInvoiceNo.value,
        invoiceDate: this.invoiceDate.value,
        createdUserId: this.userData.userId,
      };
      this.invoiceService.AddManualInvoice(manualInvoiceVm).subscribe(resp => {
        if (resp && resp.success === true) {
          this.showTopCenter('success', 'Success Message', 'Updated Manual Register Invoice Successfully');
          this.resetInvoice();
          this.GetUnBilledList();
          this.manualInvoiceList();
        }else {
          this.showTopCenter('warn', 'Failure Message', 'Manual Invoice Updating Failed');
        }
      });
    } else { this.validation('skipInvoiceNo'); this.invoiceDate.markAsTouched(); this.invoiceDate.setValidators(Validators.required); this.invoiceDate.updateValueAndValidity(); }
    }
    else {
      this.showTopCenter('info', 'Failure Message', 'Select atleast one Candidate to Updated Manual Register');
    }
  }
  monthlyChange(event: any) {
    if (event === true) {
      const date = new Date();
      this.fromDate.setValue(new Date(date.getFullYear(), date.getMonth(), 1));
      this.toDate.setValue(new Date());
    } else {
      this.fromDate.setValue('');
      this.toDate.setValue('');
    }
  }
  update() {

  }
  applyPagination() {

    this.userData.pageSize = this.ExcelFlag === true ? Number(this.shieveTotalCount) : this.shievePageSize;
    this.userData.page = this.userData.page > 0 ? this.userData.page : this.shievePageNo;
    this.userData.needTotal = true;
    this.userData.applyPaging = (this.ExcelFlag === true || this.isShowAll === true) ? false : true;

  }

  UnBilledInvoice(event: LazyLoadEvent) {
    this.loading = true;
    this.event = event;
    this.userData.page = (event.first + event.rows) / 10;
    this.userData.pageSize = 10;
    const sort = event.sortField == 'candidateName' ? 'candidateFirstName' : event.sortField
    this.userData.sorts = event.sortOrder == -1 ? "-" + sort : sort;
    this.userData.applyPaging = true;
    this.userData.needTotal = true;
    if (Object.keys(event.filters).length > 0 || event.sortField || this.userData.page) {
      if (this.clientId.value ||( this.fromDate.value && this.toDate.value)) {
      this.GetUnBilledList();
      }
    }
  }
  GetUnBilledList() {
    if (this.clientId.value && this.fromDate.value && this.toDate.value) {
      const fromDate = new Date(this.fromDate.value);
      const toDate = new Date(this.toDate.value);
      this.userData.clientId = this.clientId.value;
      this.userData.fromDate = fromDate;
      this.userData.toDate = toDate;
         this.applyPagination();
      this.invoiceService.getUnBilledInvoiceList(this.userData).subscribe(resp => {
        if (resp.body.length > 0) {
          this.unBilledInvoiceList = this.commonService.CloneObject(resp.body);
          this.loading = false;
          this.totalpages = resp.headers.get('X-Total-Count');
          this.unBilledInvoiceList?.forEach((element, i) => {
            element.listOfComponent = [];
            element.listOfComponent.push(resp[i]?.listOfComponent.map(x => x = x.subCompId > 0 ?
              x.componentName + ' - ' + x.subComponentName : x.componentName));
          });
          this.loadunbilledInvoiceList();
        } else {
          this.showTopCenter('warn', 'Failure Message', 'No Record Found');
        }
      });
    } else {
      this.validation('clientId'); this.validation('fromDate'); this.validation('toDate');
    }
    this.loadunbilledInvoiceList();
  }
  validation(ctrl: any) {
    this[ctrl].markAsTouched(); this[ctrl].setValidators(Validators.required); this[ctrl].updateValueAndValidity();
  }
  showTopCenter(level: string, info: string, message: string) {
    this.message.add({ severity: level, summary: info, detail: message });
  }
  exportExcel() {
    const expdisplayColumns = [
      { field: 'sNo', header: 'S.No' },
      { field: 'clientName', header: 'Client Name' },
      { field: 'siteName', header: 'Site Name' },
      { field: 'state', header: 'State' },
      { field: 'gstNumber', header: 'Gst Number' },
      { field: 'clientAccountManager', header: 'Client Account Manager' },
      { field: 'salesPersonName', header: 'Sales Person Name' },
      { field: 'invoiceStatus', header: 'Invoice Status' },
      { field: 'invoiceGeneratedOn', header: 'Invoice Generated On' },
      { field: 'invoiceNumber', header: 'Invoice Number' },
      { field: 'invoiceValue', header: 'Invoice Value' },
      { field: 'invoiceGeneratedBy', header: 'Invoice Generated By' }];
    
    if (this.clientId.value && this.fromDate.value && this.toDate.value) {
       this.applyPagination();         
      const fromDate = new Date(this.fromDate.value);
      const toDate = new Date(this.toDate.value) ;
        this.userData.clientId = this.clientId.value;
         this.userData.fromDate = fromDate;
          this.userData.toDate = toDate;
      this.invoiceService.getUnBilledInvoiceList(this.userData).subscribe(resp => {
        if (resp.body.length > 0) {
          this.ExcelFlag = false;
          this.unBilledInvoiceExpList = this.commonService.CloneObject(resp.body);
          this.unBilledInvoiceExpList.forEach((element, i) => {
        element.sNo = i+1;    
           });
          this.commonService.exportToExcel(expdisplayColumns, this.unBilledInvoiceExpList, this.commonService.screenName);
        }
      });
    }
    
  }
  showall() {
    if (this.unBilledInvoiceList.length > 0) {
      this.isShowAll = true;
      this.GetUnBilledList();
    }
  }
  getTotalPages(totalRecords, rows) {
    // this.totalpages = Math.ceil((totalRecords) / rows);
    return Math.ceil((totalRecords) / rows);
  }
  navigateNxtPrevPage(pageNo, rows) {
    this.currentPage = pageNo / rows;
    this.tempCurrentPage = this.currentPage;
  }
  navigatePage(pageNo, rowscount) {
    if (+pageNo > this.totalpages || +pageNo <= 0) {
      this.currentPage = this.tempCurrentPage;
    } else {
      this.dt.onPageChange({ first: ((pageNo - 1) * rowscount), rows: rowscount });
      this.tempCurrentPage = this.currentPage;
    }
  }

  private loadunbilledInvoiceList(): void {
    this.gridView = {
      data: this.unBilledInvoiceList.slice(this.skip, this.skip + this.itemperpage),
      total: this.unBilledInvoiceList.length
    };
  }
}
