import { DatePipe } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { UntypedFormControl, Validators } from '@angular/forms';
import { CommonService } from 'src/app/common-methods/services/common.service';
import { InvoiceService } from 'src/app/common-methods/services/invoice.service';
import { PageChangeEvent, GridDataResult } from '@progress/kendo-angular-grid';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/common-methods/services/auth.service';
@Component({
  standalone: false,
  selector: 'app-generate-invoice-client-list',
  templateUrl: './generate-invoice-client-list.component.html',
  styleUrls: ['./generate-invoice-client-list.component.css']
})
export class GenerateInvoiceClientListComponent implements OnInit {
  public gridView: GridDataResult;
  public buttonCount = 7;
  public info = true;
  public type: 'numeric' | 'input' = 'numeric';
  public pageSizes = true;
  public previousNext = true;
  //currentPage  = 0;
  public skip = 0;
  itemperpage = 10;
  dateType = new UntypedFormControl(null);
  fromDate = new UntypedFormControl('');
  toDate = new UntypedFormControl('');
  userData: any;
  invoiceList: any[] = [];
  displayColumns = [ { field: 'sNo', header: 'S.No' },{ field: 'clientName', header: 'Client Name' }, 
  { field: 'siteName', header: 'Site Name' },  { field: 'noOfCases', header: 'No of cases' },
  { field: 'estiMateCost', header: 'Estimate Cost (Before GST)' }, { field: 'state', header: 'State' },
  { field: 'gstNumber', header: 'GST Number' },
  { field: 'clientAccountManager', header: 'Client Account Manager' },
  { field: 'salesPersonName', header: 'Sales Person Name' },
  { field: 'invoiceStatus', header: 'Invoice Status' }, { field: 'invoiceGeneratedOn', header: 'Invoice generated on' },
  { field: 'invoiceNumber', header: 'Invoice Number' },
  { field: 'invoiceValue', header: 'Invoice Value' },
  { field: 'invoiceGeneratedBy', header: 'Invoice generated by' }];
  totalCount: number = 0;
  inputData: object = {};
  exportInvoiceList: any = []
  screenAuth: any = {};
  constructor(private invoiceService: InvoiceService, public commonService: CommonService, private datepipe: DatePipe, public router: Router, private auth: AuthService) { }

  ngOnInit() {
    this.userData = JSON.parse(sessionStorage.getItem('user_data') as string);
    this.screenAuth = this.auth.getScreenAuth(this.router.url);
    this.itemperpage=10;   
  }
  onTypeChange(value: any) {
    const date = new Date();
    if (value === null) {
      this.fromDate.reset();
      this.toDate.reset();
    } else if (value === true) {
      this.fromDate.setValue(new Date(date.getFullYear(), date.getMonth(), 1));
      this.toDate.setValue(new Date());
    } else if (value === false) {
      this.fromDate.setValue(new Date(date.getFullYear(), (date.getMonth() - 1), 1));
      this.toDate.setValue(new Date(date.getFullYear(), date.getMonth(), 0));
    }
  }
  GetGenerateList(value: any) {
    if ((value === null && this.fromDate.value && this.toDate.value) || value === true || value === false) {
      this.inputData = {
        FromDate: this.datepipe.transform(this.fromDate.value, 'yyyy-MM-dd'),
        ToDate : this.datepipe.transform(this.toDate.value, 'yyyy-MM-dd'),
        pageSize: 10,
        applyPaging: true,
        needTotal: true,
        page: 1
      };
      this.skip =0;
      this.getInvoiceClientList(this.inputData);
    } else {
      this.fromDate.markAsTouched(); this.fromDate.setValidators(Validators.required); this.fromDate.updateValueAndValidity();
      this.toDate.markAsTouched(); this.toDate.setValidators(Validators.required); this.toDate.updateValueAndValidity();
    }
    this.loadgenerateInvoiceClientList();
  }
  exportExcel() {
    this.inputData['applyPaging'] = false;
    // this.inputData['page'] = 1;
    //this.isExport = true
    //this.getInvoiceClientList(this.inputData)
    this.invoiceService.GetClientInvoiceList(this.inputData).subscribe(resp => {
      if (resp) {
        this.exportInvoiceList = resp.body;
        this.exportInvoiceList.map(d => d.invoiceGeneratedOn = this.datepipe.transform(d.invoiceGeneratedOn, 'yyyy-MM-dd'));
        this.commonService.exportToExcel(this.displayColumns, this.exportInvoiceList, this.commonService.screenName);
       }
    });
    
  }
  getInvoiceClientList(inputData: any) {
    this.invoiceService.GetClientInvoiceList(inputData).subscribe(resp => {
      if (resp) {
          this.invoiceList = resp.body;
          this.totalCount = resp.headers.get('X-Total-Count');
      }
      this.loadgenerateInvoiceClientList();
    });
  }
  showall() {
    if (this.invoiceList.length > 0) {
      this.inputData['applyPaging'] = false;
      this.inputData['page'] = 1;
      this.inputData['needTotal'] = true;
      this.getInvoiceClientList(this.inputData);
      this.itemperpage = this.invoiceList.length;
    }
  }
  showpg() {
    if (this.invoiceList.length > 0) {
      // this.itemperpage = 10;
      // this.inputData['applyPaging'] = true;
      // this.inputData['page'] = 1;
      // this.currentPage = this.inputData['page'];
      // this.inputData['pageSize'] = 10;
      // this.inputData['needTotal'] = true;
      // this.getInvoiceClientList(this.inputData)
    }
  }
  pageChange({ skip, take }: PageChangeEvent): void {
    this.skip = skip;
    this.itemperpage = take;
    this.inputData['page'] = ( skip + take ) / 10;
    this.inputData['pageSize'] = take;
    this.inputData['applyPaging'] = true;
    this.getInvoiceClientList(this.inputData);
  }

  private loadgenerateInvoiceClientList(): void {
     this.gridView = {
      data: this.invoiceList,
      total: this.totalCount
    };
  }
}
